signaller_url = "wss://ws.mirashare.app"
viewer_url = "https://mirashare.app/"
max_fps = 30

[[ice_servers]]
urls = ["stun:stun.l.google.com:19302"]

[[ice_servers]]
urls = ["turn:openrelay.metered.ca:80"]
username = "openrelayproject"
credential = "openrelayproject"
credential_type = "Password"

[encoder]
encoder = "libvpx-vp9"
pixel_format = "yuv420p"
encoding = "video/VP9"

# https://developers.google.com/media/vp9/live-encoding
[encoder.options]
deadline = "realtime"
tune-content = "screen"
max-intra-rate = "0"
tile-columns = "4"
speed = "6"
frame-parallel = "1"
threads = "8"
static-thresh = "0"
max-intra-rate = "300"
quality = "realtime"
lag-in-frames = "0"
qmin = "4"
qmax = "48"
row-mt = "1"