signaller_url = "wss://ws.mirashare.app"
viewer_url = "https://mirashare.app/"
max_fps = 60

[[ice_servers]]
urls = ["stun:stun.l.google.com:19302"]

[[ice_servers]]
urls = ["turn:openrelay.metered.ca:80"]
username = "openrelayproject"
credential = "openrelayproject"
credential_type = "Password"

[encoder]
encoder = "h264_nvenc"
yuv_input = false

[encoder.options]
profile = "baseline"
tune = "zerolatency"
<<<<<<< HEAD
preset = "p4"
=======
preset = "p7"
>>>>>>> main
tune = "ll"
zerolatency = "true"
forced-idr = "true"
