signaller_url = "wss://ws.mirashare.app"
viewer_url = "https://mirashare.app/"
max_fps = 60

[[ice_servers]]
urls = ["stun:stun.l.google.com:19302"]

[[ice_servers]]
urls = ["turn:openrelay.metered.ca:80"]
username = "openrelayproject"
credential = "openrelayproject"
credential_type = "Password"

[encoder]
encoder = "libx264"
pixel_format = "yuv420p"
encoding = "video/H264"

[encoder.options]
profile = "baseline"
tune = "zerolatency"
preset = "ultrafast"
forced-idr = "true"
